// お知らせ管理専用JavaScript

// セキュアなパスワード管理
const getAdminPassword = () => {
    // 環境変数が利用可能な場合は使用
    if (typeof process !== 'undefined' && process.env && process.env.ADMIN_PASSWORD) {
        return process.env.ADMIN_PASSWORD;
    }
    
    // ローカル開発環境でのフォールバック
    if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
        return 'dev_password_2024'; // 開発用パスワード
    }
    
    // 本番環境では入力を求める
    const savedPassword = sessionStorage.getItem('admin_master_password');
    if (savedPassword) {
        return savedPassword;
    }
    
    const password = prompt('管理者マスターパスワードを入力してください:');
    if (password) {
        sessionStorage.setItem('admin_master_password', password);
        return password;
    }
    
    return null;
};

const ADMIN_PASSWORD = getAdminPassword();

// 初期化
document.addEventListener('DOMContentLoaded', function() {
    // ログイン状態をチェック
    checkLoginStatus();
    
    // ログインフォームのイベントリスナー
    document.getElementById('loginForm').addEventListener('submit', handleLogin);
    
    // お知らせフォームのイベントリスナー
    document.getElementById('newsForm').addEventListener('submit', handleNewsSubmit);
    
    // データを読み込み
    loadNews();
    
    // サンプルデータの初期化
    initializeSampleData();
});

// ログイン処理
function handleLogin(e) {
    e.preventDefault();
    const password = document.getElementById('password').value;
    
    // パスワードが設定されていない場合のエラーハンドリング
    if (!ADMIN_PASSWORD) {
        alert('管理者パスワードが設定されていません。ページを再読み込みしてください。');
        return;
    }
    
    if (password === ADMIN_PASSWORD) {
        sessionStorage.setItem('admin_authenticated', 'true');
        showAdminContent();
        
        // パスワード入力フィールドをクリア
        document.getElementById('password').value = '';
        
        // セキュリティメッセージ
        console.log('✅ 管理者ログインが完了しました');
    } else {
        alert('パスワードが間違っています');
        // 連続失敗の記録（簡易的なセキュリティ対策）
        const failCount = parseInt(sessionStorage.getItem('login_fail_count') || '0') + 1;
        sessionStorage.setItem('login_fail_count', failCount.toString());
        
        if (failCount >= 3) {
            alert('ログイン試行回数が上限に達しました。ページを再読み込みしてください。');
            sessionStorage.removeItem('login_fail_count');
        }
    }
}

// ログイン状態チェック
function checkLoginStatus() {
    if (sessionStorage.getItem('admin_authenticated') === 'true') {
        showAdminContent();
    }
}

// 管理画面表示
function showAdminContent() {
    document.getElementById('login-form').style.display = 'none';
    document.getElementById('admin-content').style.display = 'block';
}

// ログアウト
function logout() {
    if (confirm('ログアウトしますか？')) {
        sessionStorage.removeItem('admin_authenticated');
        sessionStorage.removeItem('admin_master_password');
        sessionStorage.removeItem('login_fail_count');
        
        console.log('🔐 管理者ログアウトが完了しました');
        
        // ページをリロードしてログイン画面に戻る
        window.location.reload();
    }
}

// セクション表示（お知らせのみなので単純化）
function showSection(sectionId) {
    // お知らせセクションのみなので特に処理は不要
    console.log('お知らせセクションを表示');
}

// お知らせ送信処理
function handleNewsSubmit(e) {
    e.preventDefault();
    
    const formData = new FormData(e.target);
    const newsItem = {
        id: Date.now(),
        title: formData.get('title'),
        category: formData.get('category'),
        content: formData.get('content'),
        date: new Date().toISOString().split('T')[0]
    };
    
    console.log('お知らせ追加:', newsItem);
    
    // LocalStorageに保存
    let news = JSON.parse(localStorage.getItem('news') || '[]');
    news.unshift(newsItem); // 新しいものを先頭に
    localStorage.setItem('news', JSON.stringify(news));
    
    // フォームクリア
    e.target.reset();
    
    // 成功メッセージ表示
    showStatusMessage('news-status', 'お知らせを追加しました', 'success');
    
    // リスト更新
    loadNews();
}

// お知らせ読み込み
function loadNews() {
    const news = JSON.parse(localStorage.getItem('news') || '[]');
    const newsList = document.getElementById('news-list');
    
    console.log('お知らせ読み込み:', news.length + '件');
    
    newsList.innerHTML = '';
    
    news.forEach(item => {
        const row = document.createElement('tr');
        
        // 工事実績連携情報
        let linkInfo = '';
        if (item.autoGenerated && item.relatedWorkId) {
            linkInfo = `<br><small style="color: #2563eb;"><i class="fas fa-link"></i> 工事実績ID: ${item.relatedWorkId}から自動生成</small>`;
        }
        
        row.innerHTML = `
            <td>${item.date}</td>
            <td><span class="category-badge ${item.category}">${getCategoryName(item.category)}</span></td>
            <td>${item.title}${linkInfo}</td>
            <td class="item-actions">
                <button class="btn-admin btn-small btn-danger" onclick="deleteNews(${item.id})">削除</button>
            </td>
        `;
        newsList.appendChild(row);
    });
}

// お知らせ削除
function deleteNews(id) {
    if (confirm('このお知らせを削除しますか？')) {
        let news = JSON.parse(localStorage.getItem('news') || '[]');
        news = news.filter(item => item.id !== id);
        localStorage.setItem('news', JSON.stringify(news));
        
        showStatusMessage('news-status', 'お知らせを削除しました', 'success');
        loadNews();
    }
}

// ステータスメッセージ表示
function showStatusMessage(containerId, message, type) {
    const container = document.getElementById(containerId);
    const statusDiv = document.createElement('div');
    statusDiv.className = `status-message status-${type}`;
    statusDiv.textContent = message;
    
    container.innerHTML = '';
    container.appendChild(statusDiv);
    
    // 3秒後に消去
    setTimeout(() => {
        container.innerHTML = '';
    }, 3000);
}

// フォームクリア
function clearForm(formId) {
    document.getElementById(formId).reset();
}

// カテゴリ名取得
function getCategoryName(category) {
    const categories = {
        'info': 'お知らせ',
        'work': '施工情報',
        'important': '重要'
    };
    return categories[category] || category;
}

// サンプルデータの初期化（初回のみ）
function initializeSampleData() {
    if (!localStorage.getItem('news')) {
        const sampleNews = [
            {
                id: 1,
                title: 'ホームページをリニューアルしました',
                category: 'info',
                content: '株式会社ニシボのホームページを全面リニューアルいたしました。より使いやすく、わかりやすい構成に変更し、お客様により良い情報をお届けできるよう改善いたします。',
                date: '2024-11-06'
            },
            {
                id: 2,
                title: '大型商業施設のダイヤモンドコア工事を受注',
                category: 'work',
                content: '東京都内の大型商業施設におけるダイヤモンドコア工事を受注いたしました。安全・確実・迅速な施工でお客様のご要望にお応えしてまいります。',
                date: '2024-11-05'
            },
            {
                id: 3,
                title: '年末年始休業のお知らせ',
                category: 'important',
                content: '誠に勝手ながら、下記の期間を年末年始休業とさせていただきます。\n■休業期間：12月29日（金）～1月3日（水）\n■業務開始：1月4日（木）より通常営業\nご不便をおかけいたしますが、何卒ご理解のほどよろしくお願いいたします。',
                date: '2023-12-25'
            }
        ];
        localStorage.setItem('news', JSON.stringify(sampleNews));
        console.log('サンプルお知らせデータを初期化しました');
    }
}

console.log('お知らせ管理システム読み込み完了');